## Multi-variable linear regression

hypothesis = W(x1+x2+x3....) + b
즉, 변수가 다양하고 인스턴스도 여러개라 matrix(행렬)로 해결하는 것이 제일 효율적!

In [3]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
#instance갯수는 무한정적이니 None으로 두고 변수 갯수는 fix된 3개
X = tf.placeholder(tf.float32, shape=[None, 3])
#Result (XW = Y)
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        
# Ask my score
print("Your score will be ", sess.run(hypothesis, 
                                      feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

0 Cost:  32462.928 
Prediction:
 [[-8.492535 ]
 [-7.5766788]
 [-8.892353 ]
 [-8.673685 ]
 [-5.9843535]]
10 Cost:  1.3032 
Prediction:
 [[150.88913]
 [183.99086]
 [179.86105]
 [196.87378]
 [140.13431]]
20 Cost:  1.0048099 
Prediction:
 [[151.36996]
 [184.57149]
 [180.43178]
 [197.49504]
 [140.57806]]
30 Cost:  1.003611 
Prediction:
 [[151.37003]
 [184.57422]
 [180.43314]
 [197.49626]
 [140.58102]]
40 Cost:  1.0023987 
Prediction:
 [[151.36864]
 [184.57521]
 [180.43275]
 [197.49559]
 [140.58266]]
50 Cost:  1.0012026 
Prediction:
 [[151.36725]
 [184.57619]
 [180.43239]
 [197.49492]
 [140.58427]]
60 Cost:  1.0000004 
Prediction:
 [[151.36588]
 [184.57718]
 [180.432  ]
 [197.49426]
 [140.5859 ]]
70 Cost:  0.99882096 
Prediction:
 [[151.3645 ]
 [184.57817]
 [180.43164]
 [197.49362]
 [140.58752]]
80 Cost:  0.99763155 
Prediction:
 [[151.36311]
 [184.57913]
 [180.43126]
 [197.49294]
 [140.58913]]
90 Cost:  0.9964504 
Prediction:
 [[151.36177]
 [184.58015]
 [180.43092]
 [197.49232]
 [140.59077]

1000 Cost:  0.9061861 
Prediction:
 [[151.25331]
 [184.65802]
 [180.40218]
 [197.43637]
 [140.72269]]
1010 Cost:  0.905357 
Prediction:
 [[151.25227]
 [184.65877]
 [180.40192]
 [197.43579]
 [140.72398]]
1020 Cost:  0.904533 
Prediction:
 [[151.25125]
 [184.6595 ]
 [180.40164]
 [197.43523]
 [140.72528]]
1030 Cost:  0.90370023 
Prediction:
 [[151.25023]
 [184.66026]
 [180.40138]
 [197.43465]
 [140.72658]]
1040 Cost:  0.9028816 
Prediction:
 [[151.2492 ]
 [184.661  ]
 [180.40112]
 [197.43408]
 [140.72787]]
1050 Cost:  0.90206784 
Prediction:
 [[151.2482 ]
 [184.66173]
 [180.40086]
 [197.43352]
 [140.72916]]
1060 Cost:  0.9012389 
Prediction:
 [[151.2472 ]
 [184.66246]
 [180.4006 ]
 [197.43294]
 [140.73045]]
1070 Cost:  0.9004424 
Prediction:
 [[151.24615]
 [184.6632 ]
 [180.40033]
 [197.43237]
 [140.73172]]
1080 Cost:  0.89962834 
Prediction:
 [[151.24516]
 [184.66393]
 [180.40007]
 [197.43181]
 [140.733  ]]
1090 Cost:  0.89882165 
Prediction:
 [[151.24416]
 [184.66466]
 [180.39983]
 [197

1940 Cost:  0.83920306 
Prediction:
 [[151.16943]
 [184.71912]
 [180.38104]
 [197.38559]
 [140.83286]]
1950 Cost:  0.83859366 
Prediction:
 [[151.16867]
 [184.71968]
 [180.38086]
 [197.38507]
 [140.8339 ]]
1960 Cost:  0.83798087 
Prediction:
 [[151.16792]
 [184.72023]
 [180.38066]
 [197.38457]
 [140.83495]]
1970 Cost:  0.83738005 
Prediction:
 [[151.16714]
 [184.72078]
 [180.38048]
 [197.38405]
 [140.83598]]
1980 Cost:  0.83676463 
Prediction:
 [[151.16641]
 [184.72134]
 [180.3803 ]
 [197.38354]
 [140.83704]]
1990 Cost:  0.83616865 
Prediction:
 [[151.16565]
 [184.72191]
 [180.38011]
 [197.38306]
 [140.83809]]
2000 Cost:  0.8355743 
Prediction:
 [[151.16489]
 [184.72244]
 [180.37993]
 [197.38254]
 [140.83911]]
Your score will be  [[190.08821]]
Other scores will be  [[173.3398]
 [174.6851]]


### 파일로 데이터 읽어오기

numpy로 csv파일에 적혀있는 값을 array로 가져오면 데이터의 크기가 아무리 커도 편하게 조작 가능

In [ ]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
#전체 array 다 가져오고(:), 마지막 column 제외하고 가져오기(0:-1) = x value만 가져오기
x_data = xy[:, 0:-1]
# 결과값 y만 가져오기
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

# data output
'''
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 ...
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 ...
 [149.]
 [192.]] 
y_data shape: (25, 1)
'''